apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-routes
spec:
  hosts:
  - "*.example.com"
  gateways:
  - mesh-gateway
  http:
  - match:
    - uri:
        prefix: "/api/v1"
    route:
    - destination:
        host: api-service-v1
        subset: v1
      weight: 90
    - destination:
        host: api-service-v2
        subset: v2
      weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: circuit-breaker
spec:
  host: "*"
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        maxRequestsPerConnection: 10
        http1MaxPendingRequests: 1
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s