apiVersion: authentication.k8s.io/v1
kind: OIDCConfig
metadata:
  name: azure-ad-provider
spec:
  issuerURL: https://login.microsoftonline.com/${TENANT_ID}/v2.0
  clientID: ${CLIENT_ID}
  groupsClaim: groups
  groupsPrefix: "az:"
  requiredClaims:
    - key: "email_verified"
      value: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: environment-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-admin-binding
subjects:
- kind: Group
  name: "az:dev-team-leads"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: environment-admin
  apiGroup: rbac.authorization.k8s.io