apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/company/tenant-apps.git
      revision: HEAD
      directories:
      - path: teams/*/
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{path.basename}}'
      source:
        repoURL: https://github.com/company/tenant-apps.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values-{{path.basename}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true