groups:
  - name: FinTechAlerts
    rules:
      - alert: HighLatency
        expr: http_request_duration_seconds > 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High latency detected
          description: Service latency is above 1s for 5 minutes

      - alert: ErrorRateHigh
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.01
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: Error rate is above 1% for 5 minutes

      - alert: ComplianceViolation
        expr: compliance_check_status == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Compliance violation detected
          description: PCI-DSS compliance check failed