apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx-shard1
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rate-limit-config
  namespace: ingress-nginx
data:
  limit-req-zone-variable: "$binary_remote_addr"
  limit-req-zone-size: "10m"
  limit-req-rate: "100r/s"
  limit-req-burst: "200"
  limit-req-status-code: "429"